###Create an Approval Inbox Entry
POST http://localhost:8080/odata/v4/ManagementService/ApprovalInbox
Authorization: Basic privileged:
Content-Type: application/json

{
  "inboxEntryId": 1001,
  "leaveRequestId": "LR-1",
  "managerEmpCode": 201,
  "requestStatus": "Approved",
  "response": "Approved"
}

### Delete Approval Inbox Entry
DELETE http://localhost:8080/odata/v4/ManagementService/ApprovalInbox(1002)
Authorization: Basic privileged:
Content-Type: application/json


