### Employee Bank Details API
POST http://localhost:8080/odata/v4/ManagementService/EmployeeBankDetails
Authorization: Basic privileged:
Content-Type: application/json

{
  "BankAcNo": "12345678909781",
  "ifscCode": "ABC123456",
  "bankName": "SBI Bank",
  "accountType": "Saving",
  "empCode": 4,
  "bankAcName": "Tenva"
}




###Update Employee Bank Details
PUT http://localhost:8080/odata/v4/ManagementService/EmployeeBankDetails('12345678909781')
Authorization: Basic privileged:
Content-Type: application/json

{
  "ifscCode": "DEF987654",
  "bankName": "SBI Bank",
  "accountType": "Current",
  "bankAcName": "Ravindra"
}


###Delete Employee Bank Details
DELETE http://localhost:8080/odata/v4/ManagementService/EmployeeBankDetails('1234567892')
Authorization: Basic privileged:

###Get All Employee Bank Details
GET http://localhost:8080/odata/v4/ManagementService/EmployeeBankDetails
Authorization: Basic privileged:
