###Create a Leave Request
POST http://localhost:8080/odata/v4/ManagementService/LeaveRequest
Authorization: Basic privileged:
Content-Type: application/json

{
  "leaveRequestId": 7002,
  "empCode": 106,
  "leaveType": "Vacation",
  "startDate": "2024-04-05T00:00:00Z",
  "endDate": "2024-04-07T00:00:00Z",
  "reason": "Family Emergency",
  "status": "Approved",
  "appliedAt": "2024-03-20T14:00:00Z",
  "approvedBy": 201,
  "approvalDate": "2024-03-22T10:00:00Z"
}

###Get All Leave Requests
GET http://localhost:8080/odata/v4/ManagementService/LeaveRequest
Authorization: Basic privileged:
Content-Type: application/json

###Delete a Leave Request
DELETE http://localhost:8080/odata/v4/ManagementService/LeaveRequest(7002)
Authorization: Basic privileged:
Content-Type: application/json

