###Create a Leave Request
POST http://localhost:8080/odata/v4/ManagementService/LeaveRequest
Authorization: Basic privileged:
Content-Type: application/json

{
  "empCode": 1,
  "leaveType": "Vacation",
  "reason": "Family Emergency",
  "status": "Approved",
  "approvedBy": 201
}

###Get All Leave Requests
GET http://localhost:8080/odata/v4/ManagementService/LeaveRequest
Authorization: Basic privileged:
Content-Type: application/json

###Delete a Leave Request
DELETE http://localhost:8080/odata/v4/ManagementService/LeaveRequest('LR-1')
Authorization: Basic privileged:
Content-Type: application/json


