### Create Project
POST http://localhost:8080/odata/v4/ManagementService/Projects
Authorization: Basic privileged:
Content-Type: application/json

{
  "projectId": 12,
  "projectName": "X Project",
  "timeAssigned": 100,
  "assignedToP": 101,
  "projectChanges": 1,
  "clientName": "Client A",
  "status": "Runnig",
  "description": "Project description",
  "urgency": "High",
  "createdBy": 556,
  "modifiedBy": 556
}

### Update Project
PUT http://localhost:8080/odata/v4/ManagementService/Projects(12)
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "projectName": "Updated Project",
  "timeAssigned": 120,
  "assignedToP": 101,
  "projectChanges": 3,
  "clientName": "Client B",
  "status": "In Progress",
  "description": "Updated description",
  "urgency": "Medium",
  "createdBy": 234,
  "modifiedBy": 445
}
 

### Delete Project
DELETE http://localhost:8080/odata/v4/ManagementService/Projects(12)
Authorization: Basic privileged:
Content-Type: application/json
 
{}
 
 
### Get All Projects
GET http://localhost:8080/odata/v4/ManagementService/Projects
Authorization: Basic privileged:
 

### Create SubProject
POST http://localhost:8080/odata/v4/ManagementService/SubProjects
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "moduleId": 211,
  "projectId": 1,
  "moduleName": "P Project",
  "assignedToE": 102,
  "projectManagerId": 101,
  "timeAssigned": 80,
  "moduleStatus": "Active",
  "createdBy": 556,
  "modifiedBy": 556,
  "status":"Active"
}
 
 
### Update SubProject
PUT http://localhost:8080/odata/v4/ManagementService/SubProjects(211) 
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "moduleName": "This is a Project of Update",
  "moduleStatus": "In Progress",
  "createdBy": 556,
  "modifiedBy": 556
}



### Delete SubProject
DELETE http://localhost:8080/odata/v4/ManagementService/SubProjects(211)
Authorization: Basic privileged:


### Get All SubProjects
GET http://localhost:8080/odata/v4/ManagementService/SubProjects


  
### Create Employee
POST http://localhost:8080/odata/v4/ManagementService/Employees
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "empCode": 111,
  "empName": "SEQ",
  "projectId": 1,
  "rating": 4,
  "timeTaken": 120,
  "managerId": 103
}
 
### Update Employee
PUT http://localhost:8080/odata/v4/ManagementService/Employees(101)
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "empName": "SAM",
  "projectId": 1,
  "rating": 5,
  "timeTaken": 85
}

### Delete Employee
DELETE http://localhost:8080/odata/v4/ManagementService/Employees(111)
Authorization: Basic privileged:


### Get All Employees
GET http://localhost:8080/odata/v4/ManagementService/Employees




### ProjectReport

GET http://localhost:8080/odata/v4/ManagementService/Projects(1)

### EmployeeReport
GET http://localhost:8080/odata/v4/ManagementService/Employees(103)

### SubProjectReport
GET http://localhost:8080/odata/v4/ManagementService/SubProjects(104)
 
 
