### Create Project
POST http://localhost:8080/odata/v4/ManagementService/Projects
Authorization: Basic privileged:
Content-Type: application/json

{
  "projectId": 15,
  "projectName": "MOrning Project",
  "timeAssigned": 100,
  "assignedToP": 101,
  "projectChanges": 1,
  "clientName": "Client A",
  "status": "Runnig",
  "description": "Project description",
  "urgency": "High",
  "createdBy": 556,
  "modifiedBy": 556
}

### Get Project by ID
GET http://localhost:8080/odata/v4/ManagementService/Projects(1)
Authorization: Basic privileged:

 

### Update Project
PUT http://localhost:8080/odata/v4/ManagementService/Projects(13)
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "projectName": "Updated Project",
  "timeAssigned": 120,
  "assignedToP": 101,
  "projectChanges": 3,
  "clientName": "Client B",
  "status": "In Progress",
  "description": "Updated description",
  "urgency": "Medium",
  "createdBy": 234,
  "modifiedBy": 445
}
 

### Delete Project
DELETE http://localhost:8080/odata/v4/ManagementService/Projects(11)
Authorization: Basic privileged:
Content-Type: application/json
 
{}
 
### Get Projects by Manager (Employee ID)
GET http://localhost:8080/odata/v4/ManagementService/Projects?$filter=assignedToP eq 101
Authorization: Basic privileged:

 
 
###
 
 
### Search for Project by Name
GET http://localhost:8080/odata/v4/ManagementService/Projects?$filter=projectName eq 'DQ Project'
Authorization: Basic privileged:

###
 
### Get All Projects
GET http://localhost:8080/odata/v4/ManagementService/Projects
Authorization: Basic privileged:

 
###
 
### Filter Projects
GET http://localhost:8080/odata/v4/ManagementService/Projects?$filter=status eq 'Active' and clientName eq 'Client A' and urgency eq 'High' HTTP/1.1
Authorization: Basic privileged:

 


### Create SubProject
POST http://localhost:8080/odata/v4/ManagementService/SubProjects
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "moduleId": 210,
  "projectId": 1,
  "moduleName": "XPMY Project",
  "assignedToE": 102,
  "projectManagerId": 101,
  "timeAssigned": 80,
  "moduleStatus": "Active",
  "createdBy": 556,
  "modifiedBy": 556,
  "status":"Active"
}
 
###
 
### Get SubProject by ID
GET http://localhost:8080/odata/v4/ManagementService/SubProjects(205)
 
###

### Update SubProject
PUT http://localhost:8080/odata/v4/ManagementService/SubProjects(210) 
Content-Type: application/json
 
{
  "moduleName": "This is a Project of Update",
  "moduleStatus": "In Progress",
  "createdBy": 556,
  "modifiedBy": 556
}



### Delete SubProject
DELETE http://localhost:8080/odata/v4/ManagementService/SubProjects(207)
Authorization: Basic privileged:




 
### Get SubProjects by Project ID
GET http://localhost:8080/odata/v4/ManagementService/SubProjects?$filter=projectId eq 1

 
### Get SubProjects by Assigned Employee ID
GET http://localhost:8080/odata/v4/ManagementService/SubProjects?$filter=assignedToE eq 102
Authorization: Basic privileged:


  
### Create Employee
POST http://localhost:8080/odata/v4/ManagementService/Employees
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "empCode": 120,
  "empName": "SEQ",
  "projectId": 1,
  "rating": 4,
  "timeTaken": 120,
  "managerId": 103,
  "permissionToEdit": "YES",
  "permissionToView": "YES",
  "permissionToCreateP": "NO",
  "permissionToCreateSP": "YES",
  "permissionToCreateE": "NO"
}
 
###
 
### Get Employee by ID
GET http://localhost:8080/odata/v4/ManagementService/Employees(101)
Authorization: Basic privileged:

 
 
### Update Employee
PUT http://localhost:8080/odata/v4/ManagementService/Employees(101)
Authorization: Basic privileged:
Content-Type: application/json
 
{
  "empName": "ASDMT",
  "projectId": 1,
  "rating": 5,
  "timeTaken": 85,
  "permissionToEdit": "Yes",
  "permissionToView": "Yes",
  "permissionToCreateP": "Yes",
  "permissionToCreateSP": "Yes",
  "permissionToCreateE": "Yes"
}
 


### Search for Employee by Name
GET http://localhost:8080/odata/v4/ManagementService/Employees?$filter=empName eq ''
Authorization: Basic privileged:

 
###
 
### Get Employees by Manager ID
GET http://localhost:8080/odata/v4/ManagementService/Employees?$filter=managerId eq 103
Authorization: Basic privileged:

 
 
### Delete Employee
DELETE http://localhost:8080/odata/v4/ManagementService/Employees(120)
Authorization: Basic privileged:

 
 
 
