###Create a Team Schedule
POST http://localhost:8080/odata/v4/ManagementService/TeamSchedule
Authorization: Basic privileged:
Content-Type: application/json

{
  "ID": 401,
  "projectId": 1,
  "empCode": 2,
  "type": "Meeting",
  "remarks": "Sprint Planning Meeting"
}

###Get a Team Schedule
GET http://localhost:8080/odata/v4/ManagementService/TeamSchedule(401)
Authorization: Basic privileged:

###Update a Team Schedule
PATCH http://localhost:8080/odata/v4/ManagementService/TeamSchedule(401)
Authorization: Basic privileged:
Content-Type: application/json

{
  "ID": 401,
  "projectId": 101,
  "empCode": 1001,
  "startDateTime": "2025-02-25T10:00:00Z",
  "endDateTime": "2025-02-25T13:00:00Z",
  "type": "Meeting",
  "remarks": "Updated Sprint Planning Meeting"
}

###Delete a Team Schedule
DELETE http://localhost:8080/odata/v4/ManagementService/TeamSchedule(401)
Authorization: Basic privileged:
