spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  data-source.auto-config.enabled: false

---
spring:
  config.activate.on-profile: cloud
cds:
  index-page.enabled: true
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true

---
cds:
  datasource:
    auto-config.enabled: false
  security:
    mock:
      users:
        sumo:
            name: admin
            password: admin
            additional:
              firstName: admin

      roles:
          - Administrators
      additional:
        sumodigi:
          name: digitech
          password: digitech
          additional:
            firstName: digitech
---